// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FilePreviewController from "./file_preview_controller"
application.register("file-preview", FilePreviewController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import MenuTabsController from "./menu_tabs_controller"
application.register("menu-tabs", MenuTabsController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
